---
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Configure defined internet proxy settings
  include_tasks: proxy.yml
  args:
    apply:
      become: true
      become_method: sudo
  when: proxy_host is defined and proxy_port is defined

- name: Upgrade host and install base packages
  include_tasks: packages.yml
  args:
    apply:
      become: true
      become_method: sudo

- name: Create and manage admin accounts
  include_tasks: users.yml
  args:
    apply:
      become: true
      become_method: sudo

- name: Configure environmental settings
  include_tasks: environment.yml
  args:
    apply:
      become: true
      become_method: sudo

- name: Configure secure shell service
  include_tasks: ssh.yml
  args:
    apply:
      become: true
      become_method: sudo
...
